apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns-poweradmin.fullname" . }}-pdns-db
  labels:
    {{- include "powerdns-poweradmin.labels" . | nindent 4 }}
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.secrets.postgres.pdnsUser | quote }}
  password: {{ .Values.secrets.postgres.pdnsPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns-poweradmin.fullname" . }}-poweradmin-db
  labels:
    {{- include "powerdns-poweradmin.labels" . | nindent 4 }}
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.secrets.postgres.poweradminUser | quote }}
  password: {{ .Values.secrets.postgres.poweradminPassword | quote }}
