apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "powerdns-poweradmin.dbName" . }}
  labels:
    {{- include "powerdns-poweradmin.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.postgresql.instances }}
  imageName: {{ .Values.postgresql.imageName | quote }}

  storage:
    size: {{ .Values.postgresql.storage.size }}
    {{- with .Values.postgresql.storage.storageClass }}
    storageClass: {{ . | quote }}
    
  {{- if .Values.postgresql.walStorage.enabled }}
  walStorage:
    size: {{ .Values.postgresql.walStorage.size }}
    {{- with .Values.postgresql.walStorage.storageClass }}
    storageClass: {{ . | quote }}
    {{- end }}
  {{- end }}

  resources:
    {{- toYaml .Values.postgresql.resources | nindent 4 }}

  bootstrap:
    initdb:
      database: pdns
      owner: {{ .Values.secrets.postgres.pdnsUser }}
      secret:
        name: {{ include "powerdns-poweradmin.fullname" . }}-pdns-db
      dataChecksums: true
      postInitApplicationSQLRefs:
        configMapRefs:
          - name: {{ include "powerdns-poweradmin.fullname" . }}-pdns-schema
            key: schema.pgsql.sql

  managed:
    roles:
      - name: {{ .Values.secrets.postgres.poweradminUser }}
        ensure: present
        login: true
        passwordSecret:
          name: {{ include "powerdns-poweradmin.fullname" . }}-poweradmin-db

  postgresql:
    parameters:
      {{- toYaml .Values.postgresql.postgresql.parameters | nindent 6 }}

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname

  enablePDB: true
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: {{ include "powerdns-poweradmin.fullname" . }}-poweradmin-db
  labels:
    {{- include "powerdns-poweradmin.labels" . | nindent 4 }}
spec:
  name: poweradmin
  owner: {{ .Values.secrets.postgres.poweradminUser }}
  cluster:
    name: {{ include "powerdns-poweradmin.dbName" . }}
