apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns-poweradmin.fullname" . }}-pdns-config
  labels:
    {{- include "powerdns-poweradmin.labels" . | nindent 4 }}
type: Opaque
stringData:
  pdns.conf: |
    daemon=no
    guardian=no
    setuid=pdns
    setgid=pdns

    launch=gpgsql
    gpgsql-host={{ include "powerdns-poweradmin.dbName" . }}-rw
    gpgsql-port=5432
    gpgsql-dbname=pdns
    gpgsql-user={{ .Values.secrets.postgres.pdnsUser }}
    gpgsql-password={{ .Values.secrets.postgres.pdnsPassword }}
    gpgsql-dnssec=yes

    local-address=0.0.0.0
    local-port=53

    api=yes
    webserver=yes
    webserver-address=0.0.0.0
    webserver-port={{ .Values.powerdns.api.port }}
    webserver-allow-from={{ join "," .Values.powerdns.webserverAllowFrom }}
    api-key={{ .Values.secrets.powerdns.apiKey }}

    cache-ttl=20
    negquery-cache-ttl=60
    query-cache-ttl=20
    max-queue-msg=50000

    loglevel=4
