{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns-poweradmin.secretName" . }}
  labels:
    {{- include "powerdns-poweradmin.labels" . | nindent 4 }}
type: Opaque
stringData:
  pdns-db-username: {{ .Values.secrets.postgres.pdnsUser | quote }}
  pdns-db-password: {{ .Values.secrets.postgres.pdnsPassword | quote }}
  poweradmin-db-username: {{ .Values.secrets.postgres.poweradminUser | quote }}
  poweradmin-db-password: {{ .Values.secrets.postgres.poweradminPassword | quote }}
  powerdns-api-key: {{ .Values.secrets.powerdns.apiKey | quote }}
  poweradmin-admin-password: {{ .Values.secrets.poweradmin.adminPassword | quote }}
  poweradmin-session-key: {{ .Values.secrets.poweradmin.sessionKey | quote }}
{{- end }}
